name: Build ESP32-S3 Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Libraries
        run: |
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "WebServer"

      - name: Compile firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3:FlashSize=16M,PSRAM=enabled .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: esp32s3-firmware
          path: ./build/esp32.esp32.esp32s3/*.bin
